# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2


In [2]:
tf.__version__

'2.5.0-rc1'

# Importing Dataset

In [3]:
dataset = pd.read_csv("/Users/jayparekh/Documents/machine_learning_dataScience/Machine Learning A-Z (Codes and Datasets)/Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/Python/Churn_Modelling.csv")
independent = dataset.iloc[ : ,3 : -1].values
dependent = dataset.iloc[ : , -1].values

# Encoding Categorical Data

Label Encoding For gender Column

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
independent[ : , 2] = le.fit_transform(independent[ : , 2])

OneHot Encoding For Geography column

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
ct = ColumnTransformer(transformers = [("encoder", OneHotEncoder(), [1])], remainder = "passthrough")
independent = np.array(ct.fit_transform(independent))

In [6]:
independent[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

# Splitting Dataset Into Test Set And Training Set

In [7]:
from sklearn.model_selection import train_test_split
independent_train, independent_test, dependent_train, dependent_test = train_test_split(independent, dependent, test_size = 0.2, random_state = 0)

# Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
independent_train_scal = scalar.fit_transform(independent_train)
independent_test_scal  = scalar.transform(independent_test)

# Building ANN Model

(1) Initializing ANN

In [9]:
ann = tf.keras.models.Sequential()

(2) Adding First Hidden Layer

In [10]:
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))

(3) Adding Second Hidden Layer

In [11]:
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))

(4) Adding Output Layer

In [12]:
ann.add(tf.keras.layers.Dense(units = 1, activation = "sigmoid"))

# Train The ANN

Compiling ANN

In [13]:
ann.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

Training The ANN On The Training Set

In [14]:
ann.fit(independent_train_scal, dependent_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6694 - accuracy: 0.5944
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4728 - accuracy: 0.7963
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4516 - accuracy: 0.7934
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4294 - accuracy: 0.7964
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4203 - accuracy: 0.8020
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3981 - accuracy: 0.8283
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3861 - accuracy: 0.8364
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3766 - accuracy: 0.8424
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3529 - accuracy: 0.8567
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3529 - accura

250/250 [==============================] - 0s 1ms/step - loss: 0.3346 - accuracy: 0.8639
Epoch 81/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3338 - accuracy: 0.8681
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3435 - accuracy: 0.8610
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3301 - accuracy: 0.8660
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3325 - accuracy: 0.8673
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3442 - accuracy: 0.8568
Epoch 86/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3430 - accuracy: 0.8578
Epoch 87/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3358 - accuracy: 0.8614
Epoch 88/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3323 - accuracy: 0.8652
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3367 - accuracy: 

# Predict Result

Predict Result For Single Value

In [15]:
ann.predict(scalar.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))

array([[0.03688657]], dtype=float32)

Predict Value For Whole Test Set

In [16]:
ann.predict(independent_test_scal)

array([[0.28708577],
       [0.32920495],
       [0.19283229],
       ...,
       [0.16470164],
       [0.12373376],
       [0.19262064]], dtype=float32)