# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2


In [2]:
tf.__version__

'2.5.0-rc1'

# Importing Dataset

In [3]:
dataset = pd.read_csv("/Users/jayparekh/Documents/machine_learning_dataScience/Machine Learning A-Z (Codes and Datasets)/Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/Python/Churn_Modelling.csv")
independent = dataset.iloc[ : ,3 : -1].values
dependent = dataset.iloc[ : , -1].values

# Encoding Categorical Data

Label Encoding For gender Column

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
independent[ : , 2] = le.fit_transform(independent[ : , 2])

OneHot Encoding For Geography column

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
ct = ColumnTransformer(transformers = [("encoder", OneHotEncoder(), [1])], remainder = "passthrough")
independent = np.array(ct.fit_transform(independent))

In [6]:
independent[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

# Splitting Dataset Into Test Set And Training Set

In [7]:
from sklearn.model_selection import train_test_split
independent_train, independent_test, dependent_train, dependent_test = train_test_split(independent, dependent, test_size = 0.2, random_state = 0)

# Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
independent_train_scal = scalar.fit_transform(independent_train)
independent_test_scal  = scalar.transform(independent_test)

# Building ANN Model

(1) Initializing ANN

In [9]:
ann = tf.keras.models.Sequential()

(2) Adding First Hidden Layer

In [10]:
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))

(3) Adding Second Hidden Layer

In [11]:
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))

(4) Adding Output Layer

In [12]:
ann.add(tf.keras.layers.Dense(units = 1, activation = "sigmoid"))

# Train The ANN

Compiling ANN

In [13]:
ann.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

Training The ANN On The Training Set

In [14]:
ann.fit(independent_train_scal, dependent_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7980
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4693 - accuracy: 0.7989
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4562 - accuracy: 0.7954
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4499 - accuracy: 0.7955
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4351 - accuracy: 0.7940
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4288 - accuracy: 0.7978
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4252 - accuracy: 0.7987
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4139 - accuracy: 0.8120
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4254 - accuracy: 0.8098
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4140 - accura

250/250 [==============================] - 0s 1ms/step - loss: 0.3421 - accuracy: 0.8615
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3337 - accuracy: 0.8606
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3398 - accuracy: 0.8602
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3296 - accuracy: 0.8656
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3357 - accuracy: 0.8614
Epoch 86/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3422 - accuracy: 0.8603
Epoch 87/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3335 - accuracy: 0.8643
Epoch 88/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3344 - accuracy: 0.8604
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3214 - accuracy: 0.8726
Epoch 90/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3431 - accuracy: 

# Predict Result

Predict Result For Single Value

In [15]:
ann.predict(scalar.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))

array([[0.04157323]], dtype=float32)

Predict Value For Whole Test Set

In [16]:
dependent_pred = ann.predict(independent_test_scal)
dependent_pred = (dependent_pred > 0.5)
np.concatenate((dependent_pred.reshape(len(dependent_pred), 1), dependent_test.reshape(len(dependent_test), 1)), 1)
# dependent_pred = (dependent_pred > 0.5)
# np.stack((dependent_test, dependent_pred), axis=1)

array([[0, 0],
       [0, 1],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]])

# Making Confusion Matrix

In [17]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm = confusion_matrix(dependent_test, dependent_pred)
ac = accuracy_score(dependent_test, dependent_pred)
print(cm)
print(ac)

[[1516   79]
 [ 203  202]]
0.859
