# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Importing dataset 

In [2]:
dataset = pd.read_excel("./AirQualityUCI.xlsx")

In [3]:
import datetime as dt
import time
dataset["Date"] = pd.to_datetime(dataset["Date"])
dataset['Date'] = dataset['Date'].map(dt.datetime.toordinal)


In [4]:
dataset = dataset.drop(["Time"], axis = 1)

In [5]:
independent = dataset.iloc[ : , : 11].values
dependent = dataset.iloc[ : , 11 : 14].values

In [6]:
independent

array([[7.31650e+05, 2.60000e+00, 1.36000e+03, ..., 1.13000e+02,
        1.69200e+03, 1.26750e+03],
       [7.31650e+05, 2.00000e+00, 1.29225e+03, ..., 9.20000e+01,
        1.55875e+03, 9.72250e+02],
       [7.31650e+05, 2.20000e+00, 1.40200e+03, ..., 1.14000e+02,
        1.55450e+03, 1.07400e+03],
       ...,
       [7.32040e+05, 2.40000e+00, 1.14200e+03, ..., 1.74700e+02,
        1.24075e+03, 1.09200e+03],
       [7.32040e+05, 2.10000e+00, 1.00250e+03, ..., 1.55700e+02,
        1.04100e+03, 7.69750e+02],
       [7.32040e+05, 2.20000e+00, 1.07075e+03, ..., 1.67700e+02,
        1.12850e+03, 8.16000e+02]])

In [7]:
dependent

array([[13.5999999 , 48.87500095,  0.75775383],
       [13.29999995, 47.69999981,  0.72548745],
       [11.9000001 , 53.97500038,  0.75023907],
       ...,
       [26.89999962, 18.34999967,  0.64064877],
       [28.32499981, 13.54999995,  0.51386592],
       [28.50000048, 13.125     ,  0.50280371]])

# Splitting Dataset Into Test Set And Training Set

In [8]:
from sklearn.model_selection import train_test_split
independent_train, independent_test, dependent_train, dependent_test = train_test_split(independent, dependent, test_size = 0.2, random_state = 0)

# Training Multiple Linear Rgeression Model

In [9]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(independent_train, dependent_train)

LinearRegression()

# Predicting Future Values

In [11]:
dependent_predict = regressor.predict(independent_test)

In [12]:
dependent_predict

array([[  17.70556988,   37.74882699,    0.71250214],
       [   9.34630341,   59.16843179,    2.9874581 ],
       [  22.26051376,   50.89819979,    2.13932465],
       ...,
       [-200.48573345, -207.48067038, -198.44265118],
       [  20.09433537,   46.44516371,    1.70148379],
       [  21.34400488,   42.1440997 ,    0.73710274]])

In [13]:
dependent_test

array([[  18.82499981,   31.70000076,    0.68207458],
       [   6.07499993,   43.62500095,    0.41288352],
       [  21.50000048,   45.62499905,    1.15581658],
       ...,
       [-200.        , -200.        , -200.        ],
       [  12.5250001 ,   69.29999924,    1.00287084],
       [  31.5999999 ,   25.45000029,    1.16383758]])

# Evaluating Performance Of Model

In [14]:
from sklearn.metrics import r2_score
r2_score(dependent_test, dependent_predict)

0.9718013668195273

# Predicting Individual Value

In [17]:
regressor.predict([[732040, 3.1, 1314.25, -200, 13.529605, 1101.25, 471.7, 538.50, 189.8, 1374.25, 1728.50]])

array([[ 7.04923306, 62.71036813, -0.61882627]])