# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Importing Datasets

In [2]:
dataset = pd.read_csv("/Users/jayparekh/Documents/machine_learning_dataScience/Machine Learning A-Z (Codes and Datasets)/Part 2 - Regression/Section 5 - Multiple Linear Regression/Python/50_Startups.csv")
independent = dataset.iloc[ : , : -1].values
dependent = dataset.iloc[ : , -1].values

In [3]:
independent

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

# Handelling Null Values

In [4]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(independent[ : , : -1])
independent[ : , : -1] = imputer.transform(independent[ : , : -1])

# Encoding Categorical Data Into Numeric Data

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [3])], remainder = "passthrough")
independent = np.array(ct.fit_transform(independent))

# Splittig Dataset Into Trainnig Set And Test Set 

In [6]:
from sklearn.model_selection import train_test_split
independent_train, independent_test , dependent_train, dependent_test = train_test_split(independent, dependent, test_size=0.2, random_state=0)

# Making Multiple Regression Model From Training Set

In [7]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(independent_train, dependent_train)

LinearRegression()

# Predicting Test Set Values

In [8]:
dependent_pred = regressor.predict(independent_test)

# Visualising Predicted Values

In [9]:
print(np.concatenate((dependent_test.reshape(len(dependent_test), 1),dependent_pred.reshape(len(dependent_pred), 1)), axis = 1))


[[103282.38       103015.20159795]
 [144259.4        132582.27760816]
 [146121.95       132447.73845175]
 [ 77798.83        71976.09851258]
 [191050.39       178537.48221057]
 [105008.31       116161.24230167]
 [ 81229.06        67851.69209676]
 [ 97483.56        98791.73374687]
 [110352.25       113969.43533014]
 [166187.94       167921.06569552]]


In [10]:
pred_test_diff = abs(dependent_pred - dependent_test)
print(pred_test_diff.reshape(len(pred_test_diff), 1))

[[  267.17840205]
 [11677.12239184]
 [13674.21154825]
 [ 5822.73148742]
 [12512.90778943]
 [11152.93230167]
 [13377.36790324]
 [ 1308.17374687]
 [ 3617.18533014]
 [ 1733.12569552]]


In [ ]:
from sklearn.metrics import 