# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Importing Datset

In [2]:
dataset = pd.read_csv("./Wine.csv")
independent = dataset.iloc[ : , : -1].values
dependent = dataset.iloc[ : , -1].values

# Splitting Dataset Into Test Set And Training Set

In [3]:
from sklearn.model_selection import train_test_split
independent_train, independent_test, dependent_train, dependent_test = train_test_split(independent, dependent, random_state=0, test_size=0.2)

# Feature Scalling

In [4]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
independent_train_scal = scalar.fit_transform(independent_train)
independent_test_scal  = scalar.transform(independent_test)

# Applying LDA

In [8]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA()
independent_train_scal_lda = lda.fit_transform(independent_train_scal, dependent_train)
independent_test_scal_lda  = lda.transform(independent_test_scal)

# Making Logistic Regression Model On Training Set

In [9]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(independent_train_scal_lda, dependent_train)

LogisticRegression(random_state=0)

# Predicting Test Set values

In [11]:
dependent_pred = classifier.predict(independent_test_scal_lda)
np.stack((dependent_test, dependent_pred), axis=1)

array([[1, 1],
       [3, 3],
       [2, 2],
       [1, 1],
       [2, 2],
       [2, 2],
       [1, 1],
       [3, 3],
       [2, 2],
       [2, 2],
       [3, 3],
       [3, 3],
       [1, 1],
       [2, 2],
       [3, 3],
       [2, 2],
       [1, 1],
       [1, 1],
       [2, 2],
       [1, 1],
       [2, 2],
       [1, 1],
       [1, 1],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [3, 3],
       [1, 1],
       [1, 1],
       [2, 2],
       [1, 1],
       [1, 1],
       [1, 1]])

# Making Confusion Matrix, Checking Accuracy

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(dependent_test, dependent_pred)
ac = accuracy_score(dependent_test, dependent_pred)
print(cm)
print(ac)

[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]
1.0
