In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.11.0'

Initialization Of Tensors

In [4]:
x = tf.constant(10, shape=(1, 1), dtype=tf.float32)
x = tf.constant([[1, 2, 3], [4, 5, 6]])
x = tf.ones((2, 3))
x = tf.zeros((2, 3))
x = tf.eye((2))
x = tf.random.normal((3, 3), mean=0, stddev=1)
x = tf.random.uniform((3, 3), minval=-1, maxval=1)
x = tf.range(start=0, limit=10, delta=2)
x = tf.cast(x, dtype=tf.float32)
print(x)

tf.Tensor([0. 2. 4. 6. 8.], shape=(5,), dtype=float32)


Mathametical Operations

In [5]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])

z = tf.add(x, y)
z = x + y

z = tf.subtract(x, y)
z = x - y

z = tf.divide(x, y)
z = x / y

z = tf.multiply(x, y)
z = x * y

z = tf.tensordot(x, y, axes=1)

z = x ** 5

x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))

z = tf.matmul(x, y)
z = x @ y
print(z)

tf.Tensor(
[[-1.5846578  -0.267991   -2.0423427  -0.46624225]
 [ 1.0620031  -0.44995037  0.79296917 -1.5280147 ]], shape=(2, 4), dtype=float32)


Indexing In Tesnsors

In [15]:
x = tf.constant([1, 2, 3, 4, 5, 6, 7, 8])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)
print(x_ind)

x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
print(x[:, 1:])

tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32)
tf.Tensor([2 3 4 5 6 7 8], shape=(7,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor([1 3 5 7], shape=(4,), dtype=int32)
tf.Tensor([8 7 6 5 4 3 2 1], shape=(8,), dtype=int32)
tf.Tensor([1 4], shape=(2,), dtype=int32)
tf.Tensor(
[[2]
 [4]
 [6]], shape=(3, 1), dtype=int32)


Reshaping In Tensors

In [31]:
x = tf.range(start=0, limit=9, delta=1)
print(x)

x = tf.reshape(x, (3, 3))
print(x)

x = tf.transpose(x, perm=[1, 0])
print(x)

x = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
x = tf.transpose(x, perm=[2, 0, 1])
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[[1 3]
  [5 7]]

 [[2 4]
  [6 8]]], shape=(2, 2, 2), dtype=int32)
