# importing libraries 

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# importing datasets

In [2]:
dataset = pd.read_csv("/Users/jayparekh/Documents/machine_learning_dataScience/Machine Learning A-Z (Codes and Datasets)/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Python/Data.csv")
featureMattrix = dataset.iloc[ : , : -1].values
dependentVector = dataset.iloc[ : , -1].values

In [3]:
print(featureMattrix)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [4]:
print(dependentVector)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [5]:
print(type(featureMattrix))

<class 'numpy.ndarray'>


# Taking Care Of Missing Data

In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(featureMattrix[ : , 1 : 3])
featureMattrix[ : , 1 : 3] = imputer.transform(featureMattrix[ : , 1 : 3])

In [7]:
print(featureMattrix)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# Encoding Independent Variables

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [0])], remainder = "passthrough")
featureMattrix = np.array(ct.fit_transform(featureMattrix))

In [9]:
print(featureMattrix)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


# Encoding Dependent Variable

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dependentVector = le.fit_transform(dependentVector)


In [11]:
print(dependentVector)

[0 1 0 0 1 1 0 1 0 1]


# Splitting Dataset Into Training Set and Test Set

In [12]:
from sklearn.model_selection import train_test_split
featureMattrix_train, featureMattrix_test, dependentVector_train, dependentVector_test = train_test_split(featureMattrix, dependentVector, test_size= 0.2, random_state= 1)

In [13]:
print(featureMattrix_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [14]:
print(featureMattrix_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [15]:
print(dependentVector_train)

[0 1 0 0 1 1 0 1]


In [16]:
print(dependentVector_test)

[0 1]


# Feature Scalling

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
featureMattrix_train[ : ,3 : ] = sc.fit_transform(featureMattrix_train[ : , 3 : ])
featureMattrix_test[ : , 3 : ] = sc.transform(featureMattrix_test[ : , 3 : ])

In [18]:
print(featureMattrix_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [19]:
print(featureMattrix_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
