# Improting Libraries

In [1]:
import numpy as np
import pandas as pd

# Importing Dataset

In [2]:
dataset = pd.read_excel("./AirQualityUCI.xlsx")

In [3]:
import datetime as dt
dataset["Date"] = pd.to_datetime(dataset["Date"])
dataset["Date"] = dataset["Date"].map(dt.datetime.toordinal)
dataset = dataset.drop(["Time"], axis = 1)

In [4]:
dataset

Date  CO(GT)  PT08.S1(CO)  NMHC(GT)   C6H6(GT)  PT08.S2(NMHC)  \
0     731650     2.6      1360.00       150  11.881723        1045.50   
1     731650     2.0      1292.25       112   9.397165         954.75   
2     731650     2.2      1402.00        88   8.997817         939.25   
3     731650     2.2      1375.50        80   9.228796         948.25   
4     731650     1.6      1272.25        51   6.518224         835.50   
...      ...     ...          ...       ...        ...            ...   
9352  732040     3.1      1314.25      -200  13.529605        1101.25   
9353  732040     2.4      1162.50      -200  11.355157        1027.00   
9354  732040     2.4      1142.00      -200  12.374538        1062.50   
9355  732040     2.1      1002.50      -200   9.547187         960.50   
9356  732040     2.2      1070.75      -200  11.932060        1047.25   

      NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)       T  \
0       166.0       1056.25    113.0       1692.00      1267.50  13.600   
1       103.0       1173.75     92.0       1558.75       972.25  13.300   
2       131.0       1140.00    114.0       1554.50      1074.00  11.900   
3       172.0       1092.00    122.0       1583.75      1203.25  11.000   
4       131.0       1205.00    116.0       1490.00      1110.00  11.150   
...       ...           ...      ...           ...          ...     ...   
9352    471.7        538.50    189.8       1374.25      1728.50  21.850   
9353    353.3        603.75    179.2       1263.50      1269.00  24.325   
9354    293.0        603.25    174.7       1240.75      1092.00  26.900   
9355    234.5        701.50    155.7       1041.00       769.75  28.325   
9356    265.2        654.00    167.7       1128.50       816.00  28.500   

             RH        AH  Unnamed: 15  Unnamed: 16  
0     48.875001  0.757754          NaN          NaN  
1     47.700000  0.725487          NaN          NaN  
2     53.975000  0.750239          NaN          NaN  
3     60.000000  0.786713          NaN          NaN  
4     59.575001  0.788794          NaN          NaN  
...         ...       ...          ...          ...  
9352  29.250000  0.756824          NaN          NaN  
9353  23.725000  0.711864          NaN          NaN  
9354  18.350000  0.640649          NaN          NaN  
9355  13.550000  0.513866          NaN          NaN  
9356  13.125000  0.502804          NaN          NaN  

[9357 rows x 16 columns]

In [5]:
independent = dataset.iloc[ : , : 11].values
dependent = dataset.iloc[ : , 11 : 14].values

In [6]:
independent

array([[7.31650e+05, 2.60000e+00, 1.36000e+03, ..., 1.13000e+02,
        1.69200e+03, 1.26750e+03],
       [7.31650e+05, 2.00000e+00, 1.29225e+03, ..., 9.20000e+01,
        1.55875e+03, 9.72250e+02],
       [7.31650e+05, 2.20000e+00, 1.40200e+03, ..., 1.14000e+02,
        1.55450e+03, 1.07400e+03],
       ...,
       [7.32040e+05, 2.40000e+00, 1.14200e+03, ..., 1.74700e+02,
        1.24075e+03, 1.09200e+03],
       [7.32040e+05, 2.10000e+00, 1.00250e+03, ..., 1.55700e+02,
        1.04100e+03, 7.69750e+02],
       [7.32040e+05, 2.20000e+00, 1.07075e+03, ..., 1.67700e+02,
        1.12850e+03, 8.16000e+02]])

In [7]:
dependent

array([[13.5999999 , 48.87500095,  0.75775383],
       [13.29999995, 47.69999981,  0.72548745],
       [11.9000001 , 53.97500038,  0.75023907],
       ...,
       [26.89999962, 18.34999967,  0.64064877],
       [28.32499981, 13.54999995,  0.51386592],
       [28.50000048, 13.125     ,  0.50280371]])

# Split Dataset Into Training Set And Test Set

In [8]:
from sklearn.model_selection import train_test_split
independent_train, independent_test, dependent_train, dependent_test = train_test_split(independent, dependent, test_size = 0.2, random_state = 0)

# Training Polynomial Regression Model From Training Set

In [9]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
regressor_poly = LinearRegression()
poly_fea = PolynomialFeatures(degree = 3)
independent_train_poly = poly_fea.fit_transform(independent_train)
independent_test_poly = poly_fea.fit_transform(independent_test)
regressor_poly.fit(independent_train_poly, dependent_train)

LinearRegression()

# Predicting Future Values

In [11]:
dependent_predict = regressor_poly.predict(independent_test_poly)

In [12]:
dependent_predict

array([[  16.80794023,   34.25562538,    0.65637338],
       [   3.38121738,   48.92193975,    0.38318918],
       [  25.06287716,   42.16025166,    1.26245123],
       ...,
       [-199.68458438, -202.69308536, -200.01357961],
       [  11.96767612,   56.56182612,    0.80381361],
       [  21.4422863 ,   49.68377863,    1.17054717]])

In [13]:
dependent_test

array([[  18.82499981,   31.70000076,    0.68207458],
       [   6.07499993,   43.62500095,    0.41288352],
       [  21.50000048,   45.62499905,    1.15581658],
       ...,
       [-200.        , -200.        , -200.        ],
       [  12.5250001 ,   69.29999924,    1.00287084],
       [  31.5999999 ,   25.45000029,    1.16383758]])

# Evaluating Performance Of Model

In [14]:
from sklearn.metrics import r2_score
r2_score(dependent_test, dependent_predict)

0.9876504234602309

# Predict Single Values

In [15]:
independent

array([[ 7.31697e+05,  1.30000e+00,  9.16500e+02, ...,  7.80000e+01,
         1.31125e+03,  6.04500e+02],
       [ 7.31985e+05,  6.00000e-01,  9.18000e+02, ...,  9.16000e+01,
         8.17250e+02,  7.12000e+02],
       [ 7.31809e+05,  4.00000e-01,  7.65750e+02, ...,  4.30000e+01,
         1.30600e+03,  5.29750e+02],
       ...,
       [ 7.31680e+05,  2.60000e+00, -2.00000e+02, ...,  1.21000e+02,
        -2.00000e+02, -2.00000e+02],
       [ 7.31659e+05,  9.00000e-01,  9.98750e+02, ...,  6.30000e+01,
         1.38025e+03,  5.93500e+02],
       [ 7.31831e+05,  1.70000e+00,  9.90750e+02, ...,  8.90000e+01,
         1.41175e+03,  8.05750e+02]])

In [18]:
regressor_poly.predict(poly_fea.transform([[731650, 2.6, 1360.00, 150, 1045.50, 166, 1056.25, 113.0, 1692.00, 1267.50]]))

ValueError: X has 10 features, but PolynomialFeatures is expecting 11 features as input.

In [16]:
dataset

Date  CO(GT)  PT08.S1(CO)  NMHC(GT)   C6H6(GT)  PT08.S2(NMHC)  \
0     731650     2.6      1360.00       150  11.881723        1045.50   
1     731650     2.0      1292.25       112   9.397165         954.75   
2     731650     2.2      1402.00        88   8.997817         939.25   
3     731650     2.2      1375.50        80   9.228796         948.25   
4     731650     1.6      1272.25        51   6.518224         835.50   
...      ...     ...          ...       ...        ...            ...   
9352  732040     3.1      1314.25      -200  13.529605        1101.25   
9353  732040     2.4      1162.50      -200  11.355157        1027.00   
9354  732040     2.4      1142.00      -200  12.374538        1062.50   
9355  732040     2.1      1002.50      -200   9.547187         960.50   
9356  732040     2.2      1070.75      -200  11.932060        1047.25   

      NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)       T  \
0       166.0       1056.25    113.0       1692.00      1267.50  13.600   
1       103.0       1173.75     92.0       1558.75       972.25  13.300   
2       131.0       1140.00    114.0       1554.50      1074.00  11.900   
3       172.0       1092.00    122.0       1583.75      1203.25  11.000   
4       131.0       1205.00    116.0       1490.00      1110.00  11.150   
...       ...           ...      ...           ...          ...     ...   
9352    471.7        538.50    189.8       1374.25      1728.50  21.850   
9353    353.3        603.75    179.2       1263.50      1269.00  24.325   
9354    293.0        603.25    174.7       1240.75      1092.00  26.900   
9355    234.5        701.50    155.7       1041.00       769.75  28.325   
9356    265.2        654.00    167.7       1128.50       816.00  28.500   

             RH        AH  Unnamed: 15  Unnamed: 16  
0     48.875001  0.757754          NaN          NaN  
1     47.700000  0.725487          NaN          NaN  
2     53.975000  0.750239          NaN          NaN  
3     60.000000  0.786713          NaN          NaN  
4     59.575001  0.788794          NaN          NaN  
...         ...       ...          ...          ...  
9352  29.250000  0.756824          NaN          NaN  
9353  23.725000  0.711864          NaN          NaN  
9354  18.350000  0.640649          NaN          NaN  
9355  13.550000  0.513866          NaN          NaN  
9356  13.125000  0.502804          NaN          NaN  

[9357 rows x 16 columns]