# Importing Libraries

In [1]:
import numpy as np
import pandas as pd

# Importing Dataset

In [2]:
dataset = pd.read_csv('./heart.csv')
independent = dataset.iloc[ : , : -1].values
dependent = dataset.iloc[ : , -1].values

# Splitting Datset Into Test Set And Train Set

In [3]:
from sklearn.model_selection import train_test_split
independent_train, independent_test, dependent_train, dependent_test = train_test_split(independent, dependent, test_size = 0.2, random_state = 0)

# Feature Scalling

In [4]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
independent_train[ : , [0, 3, 4, 7]] = scalar.fit_transform(independent_train[ : , [0, 3, 4, 7]])
independent_test[ : , [0, 3, 4, 7]] = scalar.transform(independent_test[ : , [0, 3, 4, 7]])

# Training SVM Model

In [5]:
from sklearn.svm import SVC
classifier = SVC(kernel = "rbf", random_state = 0)
classifier.fit(independent_train, dependent_train)

SVC(random_state=0)

# Predicting Fututre Values

In [6]:
dependent_pred = classifier.predict(independent_test)

In [7]:
np.stack((dependent_pred, dependent_test), axis = 1)

array([[0, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [0, 1],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1]])

# Making Confusion Matrix

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(dependent_test, dependent_pred)
ac = accuracy_score(dependent_test, dependent_pred)
print(cm)
print(ac)

[[20  7]
 [ 2 32]]
0.8524590163934426


# Making Single Prediction

In [9]:
test_case = np.array([[57, 0, 0, 140, 241, 0, 1, 123, 1, 0.2, 1, 0, 3]])
test_case[ : , [0, 3, 4, 7]] = scalar.transform(test_case[ : , [0, 3, 4, 7]])
classifier.predict(test_case)

array([0])

# 