# Importing Libraries

In [1]:
import numpy as np
import pandas as pd

# Importing Dataset

In [2]:
dataset = pd.read_csv('./heart.csv')
independent = dataset.iloc[ : , : -1].values
dependent = dataset.iloc[ : , -1].values

# Splitting Datset Into Test Set And Train Set

In [3]:
from sklearn.model_selection import train_test_split
independent_train, independent_test, dependent_train, dependent_test = train_test_split(independent, dependent, test_size = 0.2, random_state = 0)

# Feature Scalling

In [4]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
independent_train[ : , [0, 3, 4, 7]] = scalar.fit_transform(independent_train[ : , [0, 3, 4, 7]])
independent_test[ : , [0, 3, 4, 7]] = scalar.transform(independent_test[ : , [0, 3, 4, 7]])

# Training KNN Model

In [5]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 10, weights = 'uniform', algorithm = 'auto', p = 2)
classifier.fit(independent_train, dependent_train)

KNeighborsClassifier(n_neighbors=10)

# Predicting Future values

In [6]:
dependent_pred = classifier.predict(independent_test)

In [7]:
np.stack((dependent_pred, dependent_test), axis = 1)

array([[0, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [0, 1],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1]])

# Making confusion Matrix

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(dependent_test, dependent_pred)
ac = accuracy_score(dependent_test, dependent_pred)
print(cm)
print(ac)

[[19  8]
 [ 3 31]]
0.819672131147541


In [9]:
dataset.tail()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0

# Predicting Single Value 

In [10]:
test_case = np.array([[45, 1, 3, 110, 264, 0, 1, 132, 0, 1.2, 1, 0, 3]])
test_case[ : , [0, 3, 4 ,7]] = scalar.transform(test_case[ : , [0, 3, 4, 7]])
classifier.predict(test_case)

array([1])